keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate: 10
paginate_path: "blog/page:num"


name: showzeng
description:  showzeng's blog
url: http://showzeng.itscoder.com/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

gems:
  - jekyll-feed
  - rouge
  - jekyll-paginate
  - kramdown
exclude:
  - Gemfile
  - Gemfile.lock
